### ISSUE TITLE
Incompatible with Symphony 3

### ISSUE THREAD

**Issue by BramDriesen** [jhedstrom/drupalextension#423] opened 2017-12-01 07:37 UTC
When being upgraded to Symphony 3. DrupalExtension becomes incompatible because of the use of plain scalars without quoting them.

> The file ".../behat/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/ServiceContainer/config/services.yml" does not contain valid YAML.

> The reserved indicator "%" cannot start a plain scalar; you need to quote the scalar at line 34 (near "class: %drupal.drupal.class%").

**Comment by jhedstrom** [comment] 2017-12-01 18:26
Thanks again!

**Comment by alexfinnarn** [comment] 2017-12-06 18:31
I'd like to see this issue reopened due to https://github.com/jhedstrom/drupalextension/blob/master/src/Drupal/DrupalExtension/ServiceContainer/config/services.yml#L49 and potentially other places in the code. 

I just switched to ` "drupal/drupal-extension": "dev-master"` via Composer and got the same error as above.

**Comment by jhedstrom** [comment] 2017-12-06 19:07
Is this resolved with your PR in #439 now?

**Comment by alexfinnarn** [comment] 2017-12-06 20:29
@jhedstrom it does appear to fix my issue, thanks! 

I'm not sure if contributors are remembering to add quotes though and if my issue is caused by added code since the previous commits. I don't know if you can make that more explicit when adding/reviewing code or add a test that would point out invalid YAML according to...I don't really know what validates the YAML.

You can close for now or try another find and replace for other non-quoted strings.

**Comment by jhedstrom** [comment] 2017-12-06 20:37
@alexfinnarn to prevent it from regressing in the future, I suppose we should be testing against symfony 3 (although we do test against Drupal 8.4, which uses symfony 3, so I'm not sure what else is to be done)...

**Comment by alexfinnarn** [comment] 2017-12-06 20:59
Makes sense. Can you try adding that to the matrix somehow? I'm surprised it works in Drupal 8 but not in my case...I'm trying this on a Drupal 7 site though so no composer install of Drupal's codebase for me.

**Comment by jhedstrom** [comment] 2017-12-06 21:04
I've opened #442 so we don't lose track of this.

**Closed by jhedstrom** 2017-12-06 21:04 UTC
Labels: bug
