### ISSUE TITLE
LoggedIn() doesn't wait for page to load

### ISSUE THREAD

**Issue by zuernBernhard** [jhedstrom/drupalextension#364] opened 2017-04-11 13:41 UTC
Given I am logged in as a user with the "XXX" role

fails here because the login-link is checked before the page is loaded. 

If I change 

```
/**
   * Log-in the given user.
   *
   * @param \stdClass $user
   *   The user to log in.
   */
  public function login(\stdClass $user) {
    $manager = $this->getUserManager();

    // Check if logged in.
    if ($this->loggedIn()) {
      $this->logout();
    }

    $this->getSession()->visit($this->locatePath('/user'));
    $element = $this->getSession()->getPage();
    $element->fillField($this->getDrupalText('username_field'), $user->name);
    $element->fillField($this->getDrupalText('password_field'), $user->pass);
    $submit = $element->findButton($this->getDrupalText('log_in'));
    if (empty($submit)) {
      throw new \Exception(sprintf("No submit button at %s", $this->getSession()->getCurrentUrl()));
    }

    // Log in.
    $submit->click();
    if (!$this->loggedIn()) {
      if (isset($user->role)) {
        throw new \Exception(sprintf("Unable to determine if logged in because 'log_out' link cannot be found for user '%s' with role '%s'", $user->name, $user->role));
      }
      else {
        throw new \Exception(sprintf("Unable to determine if logged in because 'log_out' link cannot be found for user '%s'", $user->name));
      }
    }

    $manager->setCurrentUser($user);
  }
```

to (by adding the sleep() ):

```
/**
   * Log-in the given user.
   *
   * @param \stdClass $user
   *   The user to log in.
   */
  public function login(\stdClass $user) {
    $manager = $this->getUserManager();

    // Check if logged in.
    if ($this->loggedIn()) {
      $this->logout();
    }

    $this->getSession()->visit($this->locatePath('/user'));
    $element = $this->getSession()->getPage();
    $element->fillField($this->getDrupalText('username_field'), $user->name);
    $element->fillField($this->getDrupalText('password_field'), $user->pass);
    $submit = $element->findButton($this->getDrupalText('log_in'));
    if (empty($submit)) {
      throw new \Exception(sprintf("No submit button at %s", $this->getSession()->getCurrentUrl()));
    }

    // Log in.
    $submit->click();

    // DIRTY HACK: Wait for the page to load.
    sleep(5);

    if (!$this->loggedIn()) {
      if (isset($user->role)) {
        throw new \Exception(sprintf("Unable to determine if logged in because 'log_out' link cannot be found for user '%s' with role '%s'", $user->name, $user->role));
      }
      else {
        throw new \Exception(sprintf("Unable to determine if logged in because 'log_out' link cannot be found for user '%s'", $user->name));
      }
    }

    $manager->setCurrentUser($user);
  }
```

It works like a charm.

Using 
* behat 3.1.0
* Drupal-Extension dev-master, 4.0.x-dev
* Docker to run Selenium: selenium/standalone-firefox-debug:latest

How is it possible to really wait for the page to load before the login link is checked ?

**Comment by pfrenssen** [comment] 2017-04-12 17:22
I believe the webdriver waits until the page is loaded before continuing so the sleep should not be needed. Are you populating things dynamically on the page with JS, or are you running something like BigPipe?

**Comment by jhedstrom** [comment] 2017-12-05 19:13
Closing as a duplicate of #325 for now. Feel free to re-open if this is not the same issue.

**Closed by jhedstrom** 2017-12-05 19:13 UTC
