### ISSUE TITLE
Support Symfony 3

### ISSUE THREAD

**Issue by tstoeckler** [jhedstrom/drupalextension#372] opened 2017-05-02 10:15 UTC
The Symfony dependencies in `composer.json` are currently declared as:
```
    "symfony/dependency-injection": "~2.7",
    "symfony/event-dispatcher": "~2.7"
```
which prevents installing the Drupal extension alongside Symfony 3, for example with latest Drupal 8.4.x.

**Comment by jhedstrom** [comment] 2017-05-02 20:15
hmm, this should have been fixed years ago in #232...

**Comment by tstoeckler** [comment] 2017-05-03 07:51
At that time there were no explicit dependencies on Symfony as far as I can tell, so that was just about the drupal-driver compatibility. The dependencies were introduced in https://github.com/jhedstrom/drupalextension/commit/0d658de9740956701dd43e90dc2eae92459dcdac but not sure why exactly.

**Comment by jhedstrom** [comment] 2017-05-03 20:53
Hopefully this can be resolved in #324.

**Comment by haringsrob** [comment] 2017-06-08 15:50
Will be closed by #324

**Comment by pfrenssen** [comment] 2017-06-08 16:32
Closing as duplicate of #324.

**Closed by pfrenssen** 2017-06-08 16:32 UTC
Labels: bug
