### ISSUE TITLE
Chromedriver with Chrome 55, 56, 57, 58+ seems to not work

### ISSUE THREAD

**Issue by geerlingguy** [jhedstrom/drupalextension#370] opened 2017-04-28 21:08 UTC
It seems that if you try using the Drupal Extension for Behat with the latest Chromedriver version/Selenium, as well as the latest Chrome version (58 as of this writing), `@javascript` tests always fail with something like:

```
      Could not open connection: chrome not reachable
        (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-31-generic x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 114.36 seconds
      Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
      System info: host: 'drupalvm', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-31-generic', java.version: '1.8.0_121'
      Driver info: org.openqa.selenium.chrome.ChromeDriver (Behat\Mink\Exception\DriverException)
```

I can reproduce this issue using Drupal VM pretty easily, and it seems the problem cropped up sometime around when Chrome 54 or 55 was released. Chromedriver _says_ it's compatible with the latest releases... but it seems not to be working.

See the latest notes on this issue / reproducibility here: https://github.com/geerlingguy/drupal-vm/issues/1152#issuecomment-298083189

And see a potential related upstream bug report in the chromium project here: https://bugs.chromium.org/p/chromium/issues/detail?id=716175&can=2&start=0&num=100&q=chromedriver&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

**Comment by pfrenssen** [comment] 2017-06-16 10:43
For me Chrome has been working fine in Selenium for the past 2 years or so. I am using the official docker containers provided by the Selenium team at https://github.com/SeleniumHQ/docker-selenium - the containers keep the versions of Selenium - webdriver - browser in sync and this is working out great. I am updating the containers at least once a week.

On another note I think that this is probably not the responsibility of DrupalExtension. We are not interfacing with Selenium directly but are leveraging third party libraries for this which are bundled in the main Behat project. This sounds more like something for https://github.com/minkphp/Mink/ or https://github.com/Behat/MinkExtension/ . I will close this for that reason.

If this is still a problem, could you try if this problem also occurs with vanilla Behat / Mink?

If you are sure this is caused by DrupalExtension itself feel free to comment and I will reopen.

**Closed by pfrenssen** 2017-06-16 10:43 UTC
