### ISSUE TITLE
Encountered Recoverable Fatal Error

### ISSUE THREAD

**Issue by mohankumargupta** [jhedstrom/drupalextension#170] opened 2015-05-11 04:52 UTC
I'm running behat on Travis CI and encountered an error today. It has been working fine for the last month or so.

$ behat -c ./modules/mentions/behat.yml
Recoverable fatal error: Object of class Drupal\Core\Extension\Extension could not be converted to string in Drupal\Component\Utility\SafeMarkup::isSafe() (line 94 of /home/travis/build/mohankumargupta/mentionsdrupal8module/web/mydrupal/drupal-8.0.x/core/lib/Drupal/Component/Utility/SafeMarkup.php).
The command "behat -c ./modules/mentions/behat.yml" exited with 0.

Project I am working on:
https://github.com/mohankumargupta/mentionsdrupal8module

Travis CI 
Build 161 has the error mentioned above
https://travis-ci.org/mohankumargupta/mentionsdrupal8module/builds/61956724#L708

Build 160 works fine
https://travis-ci.org/mohankumargupta/mentionsdrupal8module/builds/61572472#L904

The commit that triggers the build 161 does not modify behat.yml, so I'm assuming it's something with the drupal extension (is that right?)

https://github.com/mohankumargupta/mentionsdrupal8module/commit/7cfbea9cf0b36b3bf4d4871ef1b488b4cae8cc54

**Comment by mohankumargupta** [comment] 2015-05-15 02:29
I'm using drupal 8.0.x and drupal extension 3.0.10.

The offending line is:

 core/vendor/drupal/drupal-driver/src/Drupal/Driver/DrupalDriver.php line 137

 $paths[] = $this->drupalRoot . DIRECTORY_SEPARATOR . \drupal_get_path('module', $module);

Problem is argument 2 is of type Drupal\Core\Extension\Extension, whereas it expects a string 

My fix for Drupal 8 is:

 $paths[] = $this->drupalRoot . DIRECTORY_SEPARATOR . \drupal_get_path('module', $module->getName());

I also noticed that bootstrap.inc uses

      foreach (\Drupal::moduleHandler()->getModuleList() as $module_name => $module) {
        $files[$type][$module_name] = $module->getPathname();
      }

Also
https://www.drupal.org/node/2198695

I'm not an expert (just trying to do some detective work), so if I'm off the mark, let me know.

**Comment by jhedstrom** [comment] 2015-05-15 23:19
This was caused by a change in D8 core. Added a PR over at https://github.com/jhedstrom/DrupalDriver/pull/32. Closing this out for now.

**Closed by jhedstrom** 2015-05-15 23:19 UTC
